---
- name: Provision inetRouter
  hosts: inetRouter
  become: yes

  vars:
    sysctl_params:
      net.ipv4.ip_forward: "1"

  roles:
    - network-lab

- name: Provision CentralRouter
  hosts: centralRouter
  become: yes

  vars:
    sysctl_params:
      net.ipv4.ip_forward: "1"
      net.ipv4.conf.all.forwarding: "1"
    interfaces:
      - device: "eth2:0"
        ipaddr: "192.168.0.33"
        netmask: "255.255.255.240"
      - device: "eth2:1"
        ipaddr: "192.168.0.65"
        netmask: "255.255.255.192"
    routes:
      - dest: "192.168.2.64/26"
        via: "192.168.2.1"
      - dest: "192.168.1.128/26"
        via: "192.168.1.1"

  roles:
    - network-lab

- name: Provision CentralServer
  hosts: centralServer
  become: yes

  roles:
    - network-lab

- name: Provision Office1Router
  hosts: office1Router
  become: yes

  vars:
    sysctl_params:
      net.ipv4.ip_forward: "1"
      net.ipv4.conf.all.forwarding: "1"
    interfaces:
      - device: "eth1:0"
        ipaddr: "192.168.2.129"
        netmask: "255.255.255.192"
      - device: "eth1:1"
        ipaddr: "192.168.2.193"
        netmask: "255.255.255.192"

  roles:
    - network-lab

- name: Provision Office1Server
  hosts: office1Server
  become: yes

  roles:
    - network-lab

- name: Provision Office2Router
  hosts: office2Router
  become: yes

  vars:
    sysctl_params:
      net.ipv4.ip_forward: "1"
      net.ipv4.conf.all.forwarding: "1"
    interfaces:
      - device: "eth1:0"
        ipaddr: "192.168.1.193"
        netmask: "255.255.255.192"

  roles:
    - network-lab

- name: Provision Office2Server
  hosts: office2Server
  become: yes

  roles: 
    - network-lab
